version: '3.9'
services:
    jenkins:
        image: jenkins/jenkins:lts
        privileged: true
        user: root
        ports:
        - 8000:8000
        - 50000:50000
        container_name: jenkins
        # volumes:
        #    - /home/${myname}/jenkins_compose/jenkins_configuration:/var/jenkins_home
        #     - /var/run/docker.sock:/var/run/docker.sock

    angular:  # name of the first service
      # build: frontend # specify the directory of the Dockerfile
      container_name: angular
      build: .
      ports:
        - "4200:4200" # specify port forewarding
      # image: pravinbhogulkar/codewithpravinbhogulkar:frontend
        
    node:  #name of the second service
      # container_name: express
      # build: backend # specify the directory of the Dockerfile
      container_name: node
      build: .
      restart: always
      ports:
        - "3000:3000" #specify ports forewarding
      # image: pravinbhogulkar/codewithpravinbhogulkar:backend

            # links:
        #   - mongo
    
            # mongo:  # name of the third service
                    #   # container_name: mongo
                    #   # image: mongo # specify image to build container from
                    #   ports:
                    #     - "27017:27017" # specify port forewarding
# agent:
#     image: jenkins/ssh-agent:jdk11
#     privileged: true
#     user: root
#     container_name: agent
#     expose:
#       - 22
#     environment:
#       - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7ngQknqwzJlqBEsdnVYFqO90m29mOCII9yoCLZbo/pjnHpRBLDjSJof0wNjflRpTUSgiWw2ShTcmbyVxHO2kIGeSIDLnXXUpO5n5UXyY+NJubslwsMiB4j8A0I5dubcYAOBoKV+Mw0MhCmDWQWfkYlZ434Fu2jE4/xP6QcR1CQ07Z3/8gWUehhrjkM5bWgDbIfWa34hOOu/5YmmEa+SwWGHPb33QlGerkF0TWpcTgt0gxr0JVcdHnAvsLQPZHrgp5RsXQapidzn+s0pEjFks18MOsnle86VHhPtGuWO91PAbwO5gUQNWiUO0h2RDWmfZZTnhIoNjg3VkVUKp/HgJl/+HhlMlUzWgkTv6V/QILke53ikY4lA8CU3at7zjOQSHZU7vW6//M8PW0e+ESRqT0qYIQyzftAj3BRKzC69XnK6YstZHCV5mZjiYiP+V7Ef/rQIBB3H19AGSDNIBVuygnme3PLSH81YhMqpQ35ky3avXoKlO1fqyQltNC1Ywg6x0= emeaad\pbhogulkar@ITEM-S138219
